version: '3.8'

services:

  nginx:
    build: ./compose/production/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
      
  web:
    build: 
      context: ./
      dockerfile: ./compose/production/django/Dockerfile.prod
    command: gunicorn a_config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.envs/.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume:

