version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: gunicorn a_config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mikdik
      - POSTGRES_DB=collector_dev

volumes:
  postgres_data: