# Generated by Django 5.0.2 on 2024-03-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
