# Generated by Django 5.0.2 on 2024-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0002_release_barcode_release_date_release_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
