# Generated by Django 5.0.2 on 2024-02-14 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.AddField(
            model_name='media',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='record_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_labels', to='a_collections.record_label'),
        ),
    ]
