# Generated by Django 5.0.2 on 2024-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0003_release_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='cd_tracks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='dvd_tracks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
