# Generated by Django 5.0.2 on 2024-03-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0003_record_label_remove_artist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='record_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_labels', to='a_collections.record_label'),
        ),
    ]
