# Generated by Django 5.0.2 on 2024-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0006_remove_cover_art_cover_art_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_label',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
