# Generated by Django 5.0.2 on 2024-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0006_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='ext_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
