# Generated by Django 5.0.2 on 2024-03-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0007_artist_ext_score_artist_musicbrainz_id_artist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
