# Generated by Django 5.0.2 on 2024-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0008_alter_artist_musicbrainz_id_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
