# Generated by Django 5.0.2 on 2024-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0008_rename_type_collection_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_art',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_art/'),
        ),
    ]
