# Generated by Django 5.0.2 on 2024-03-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0009_media_musicbrainz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='title',
            new_name='name',
        ),
    ]
