# Generated by Django 5.0.2 on 2024-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0010_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
