# Generated by Django 5.0.2 on 2024-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_collections', '0013_alter_release_options_remove_release_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_group',
            name='secondary_type_ids',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='release_group',
            name='secondary_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='release_group',
            name='primrary_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
